version: '3.8'

services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: dynamodb-local
        ports:
            - '8000:8000'
        command: -jar DynamoDBLocal.jar -sharedDb
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'curl -s http://localhost:8000 > /dev/null || exit 1',
                ]
            interval: 5s
            retries: 5
        networks:
            - backend-network

    dynamodb-init:
        image: amazon/aws-cli
        depends_on:
            dynamodb:
                condition: service_healthy
        entrypoint: ['/bin/sh', '-c']
        environment:
            AWS_DEFAULT_REGION: us-west-2
            AWS_ACCESS_KEY_ID: dummy
            AWS_SECRET_ACCESS_KEY: dummy
        command: >
            "
            echo 'Esperando a DynamoDB Local...';
            until curl -s http://dynamodb:8000 > /dev/null; do
              sleep 2;
            done;
            echo 'DynamoDB Local está listo. Creando tablas...';
            aws dynamodb create-table \
              --table-name FusionadosHistory \
              --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
              --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST \
              --endpoint-url http://dynamodb:8000 &&
            aws dynamodb create-table \
              --table-name StarWarsPlanets \
              --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
              --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
              --billing-mode PAY_PER_REQUEST \
              --endpoint-url http://dynamodb:8000;
            echo 'Tablas creadas exitosamente.';
            "
        networks:
            - backend-network
        restart: 'no'

networks:
    backend-network:
        name: backend-softtek-challenge
