service: backend-softtek-challenge

frameworkVersion: '4'

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-2
    stage: dev
    # Permisos necesarios (opcional), puedes agregar policies o roles

plugins:
    - serverless-offline

functions:
    createUser:
        handler: src/interface/lambda/handlers/userHandler.createUserHandler
        events:
            - http:
                  path: users
                  method: post

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        target: 'node20'
        platform: 'node'
        concurrency: 10
        tsconfig:
            'tsconfig.json'

            # Si tu archivo se llama src/handler.ts, con la exportación 'handler',
            # esbuild se encarga de generar un output con esa función.

        # Config para serverless-offline (opcional)
        # serverless-offline:
        #   port: 3000
        #   host: 0.0.0.0
        #   noPrependStageInUrl: true
