service: mi-proyecto-clean-architecture
frameworkVersion: '4'

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-1
    stage: dev

functions:
    # Ejemplo: Endpoints para Star Wars People
    getPeople:
        handler: src/interface/lambda/handlers/swapiPeopleHandler.getPeopleHandler
        events:
            - http:
                  path: fusionados/people
                  method: get

    getPersonById:
        handler: src/interface/lambda/handlers/swapiPeopleHandler.getPersonByIdHandler
        events:
            - http:
                  path: fusionados/people/{id}
                  method: get

    # Ejemplo anterior: createUser
    createUser:
        handler: src/interface/lambda/handlers/userHandler.createUserHandler
        events:
            - http:
                  path: users
                  method: post

plugins:
    - serverless-offline

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        target: 'node20'
        platform: 'node'
        concurrency: 10
        # tsconfig: 'tsconfig.json'
